
name: learn-github-actions
on: push
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setups-node@v4
        with: 
          node-version: '20'
      - run: npm i -g bats
      - run: bats - v

